//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAppLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int RentalID { get; set; }
        public int CustomerID { get; set; }
        public int MovieID { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
