//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Authentication
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "User name is required")]
        public string User { get; set; }

        [Required(ErrorMessage = "User password is required")]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }

        public string ErrorMessageUs { get; set; }

    }
}
